#!/usr/bin/env node
/**
 * Generates docs/industry_scenario_prompts.md: which prompt each predefined AI
 * scenario sends for every customer-theme industry.
 *
 * The code is the source of truth (INDUSTRIES in src/utils/customerTheme.js,
 * the default prompts in src/services/defaultSettings.ts); this doc is a
 * projection of it for presenters.
 *
 *   npm run docs:industry-prompts              # rewrite the doc
 *   npm run docs:industry-prompts -- --check   # fail if the doc is stale
 */
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync, rmSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { INDUSTRIES, OVERRIDABLE_PROMPTS, SCENARIO_LABELS } from '../src/utils/customerTheme.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const UI_DIR = path.resolve(__dirname, '..');
const OUT = path.resolve(UI_DIR, '..', 'docs/industry_scenario_prompts.md');
const checkOnly = process.argv.includes('--check');

// defaultSettings.ts is a Vite module; bundle it to plain ESM (as generate_scenario_presets_doc.mjs does).
const work = mkdtempSync(path.join(tmpdir(), 'industry-prompts-'));
const bundle = path.join(work, 'defaultSettings.mjs');
let defaults;
try {
  execFileSync(
    path.join(UI_DIR, 'node_modules/.bin/esbuild'),
    [path.join(UI_DIR, 'src/services/defaultSettings.ts'), '--bundle', '--format=esm', '--platform=node', `--outfile=${bundle}`, '--define:import.meta.env={}', '--log-level=error'],
    { stdio: 'inherit' }
  );
  defaults = await import(pathToFileURL(bundle).href);
} finally {
  rmSync(work, { recursive: true, force: true });
}

const defaultPrompt = {};
for (const list of ['UNAUTHORIZED_401_EXAMPLES', 'MODEL_ARMOR_EXAMPLES', 'AUTO_ROUTING_EXAMPLES', 'TOKEN_LIMIT_EXAMPLES', 'CACHE_EXAMPLES']) {
  for (const e of defaults[list] || []) defaultPrompt[e.id] = e.prompt;
}

const cell = (s) => String(s || '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
const industries = INDUSTRIES.filter((i) => i.id !== 'generic');
const lines = [
  '# Industry scenario prompts',
  '',
  '<!-- Generated by ui/scripts/generate_industry_prompts_doc.mjs. Do not edit by hand. -->',
  '',
  'When a customer theme sets an industry, each predefined AI-tab scenario sends the prompt below instead of the default.',
  'Each prompt keeps the shape its outcome depends on (router category, cache similarity, token size, Model Armor signal); see the comment above `INDUSTRIES` in `ui/src/utils/customerTheme.js`.',
  'MCP and agent scenarios call tools with fixed demo data, so they are not mapped.',
  'These are the built-in industries. Industries the theme agent adds for customers that fit none of them live in the theme bucket (`industries/<id>.json`) and use the templates in `ui/server/industryGenerator.js`.',
  '',
  `Industries: ${industries.map((i) => `[${i.label}](#${i.label.toLowerCase().replace(/[^a-z0-9 -]/g, '').replace(/ /g, '-')})`).join(' · ')}`,
  '',
  '## Default (no industry)',
  '',
  '| Scenario | Prompt |',
  '| --- | --- |',
  ...OVERRIDABLE_PROMPTS.map((id) => `| ${cell(SCENARIO_LABELS[id])} | ${cell(defaultPrompt[id])} |`),
];
for (const i of industries) {
  lines.push('', `## ${i.label}`, '', `Personas: ${Object.values(i.personas).map((p) => p.label).join(' · ')}`, '', '| Scenario | Prompt |', '| --- | --- |');
  for (const id of OVERRIDABLE_PROMPTS) lines.push(`| ${cell(SCENARIO_LABELS[id])} | ${cell(i.prompts[id] || `(default) ${defaultPrompt[id] || ''}`)} |`);
}
const doc = lines.join('\n') + '\n';

if (checkOnly) {
  const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
  if (current !== doc) {
    console.error(`${path.relative(process.cwd(), OUT)} is stale. Run: npm run docs:industry-prompts`);
    process.exit(1);
  }
  console.log('industry prompt doc is up to date');
} else {
  writeFileSync(OUT, doc);
  console.log(`wrote ${path.relative(process.cwd(), OUT)}`);
}
