#!/usr/bin/env node
// Writes industries/MAPPING.md: one table of what each industry drives in the demo.
//
//   industry -> AI-tab prompts + persona names   (INDUSTRIES in ui/src/utils/customerTheme.js)
//   industry -> MCP server, Apigee products, tools, Agent Showcase   (industries/<id>.json)
//   theme    -> industry   (customer theme library in GCS; snapshot in mapping/themes.json)
//
//   node industries/mapping.mjs                     # regenerate MAPPING.md
//   node industries/mapping.mjs --check             # exit 1 if MAPPING.md is stale (tests)
//   node industries/mapping.mjs --refresh-themes [url]
//        # re-read the theme library (default http://localhost:3000/api/themes) into the snapshot

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { INDUSTRIES, OVERRIDABLE_PROMPTS } from '../ui/src/utils/customerTheme.js';

const DIR = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(DIR, 'MAPPING.md');
const SNAPSHOT = path.join(DIR, 'mapping', 'themes.json');

function packs() {
  return fs.readdirSync(DIR).filter((f) => f.endsWith('.json')).sort()
    .map((f) => JSON.parse(fs.readFileSync(path.join(DIR, f), 'utf8')));
}

function snapshot() {
  if (!fs.existsSync(SNAPSHOT)) return { themes: [], industries: [] };
  return JSON.parse(fs.readFileSync(SNAPSHOT, 'utf8'));
}

async function refreshThemes(url) {
  const r = await fetch(url);
  if (!r.ok) throw new Error(`${url}: HTTP ${r.status}`);
  const body = await r.json();
  const snap = {
    source: url.replace(/localhost:\d+/, 'localhost'),
    themes: (body.themes || []).map((t) => ({ id: t.id, name: t.name, industry: t.industry || 'generic' })).sort((a, b) => a.id.localeCompare(b.id)),
    industries: (body.industries || []).map((i) => ({ id: i.id, label: i.label, source: i.source || 'agent', personas: i.personas || {}, prompts: Object.fromEntries(Object.keys(i.prompts || {}).map((k) => [k, true])) })).sort((a, b) => a.id.localeCompare(b.id)),
  };
  fs.writeFileSync(SNAPSHOT, JSON.stringify(snap, null, 2) + '\n');
  console.log(`mapping/themes.json: ${snap.themes.length} themes, ${snap.industries.length} added industries`);
}

const esc = (s) => String(s).replace(/\|/g, '\\|');

export function render(allPacks = packs(), snap = snapshot()) {
  const byId = new Map(allPacks.map((p) => [p.id, p]));
  const themesFor = (id) => snap.themes.filter((t) => t.industry === id).map((t) => t.name);
  const promptIds = OVERRIDABLE_PROMPTS.map((p) => (typeof p === 'string' ? p : p.id));
  const industries = [
    ...INDUSTRIES.map((i) => ({ ...i, source: 'built-in' })),
    ...snap.industries.filter((i) => !INDUSTRIES.some((b) => b.id === i.id)).map((i) => ({ personas: {}, prompts: {}, ...i, source: 'added by the theme agent' })),
  ];
  const withPack = industries.filter((i) => byId.has(i.id)).length;
  const L = [];
  L.push('# Industry mapping');
  L.push('');
  L.push('Generated by `node industries/mapping.mjs` from `ui/src/utils/customerTheme.js`, `industries/*.json` and `industries/mapping/themes.json`. Do not edit by hand.');
  L.push('');
  L.push('The active theme picks the industry. The industry then picks the AI-tab prompts and persona names, and, if it has a pack, the MCP server, tools, Apigee products and Agent Showcase agents. Without a pack the MCP tab and Agent Showcase use the generic Customer Service tools.');
  L.push('');
  L.push(`**${withPack} of ${industries.length} industries have a pack.**`);
  L.push('');
  L.push('## Industries');
  L.push('');
  L.push('| Industry | AI-tab prompts | Personas (Support / Analysts / Admin) | MCP server | Tools (ops / insights / all) | Agent Showcase | Themes |');
  L.push('|---|---|---|---|---|---|---|');
  for (const i of industries) {
    const p = byId.get(i.id);
    const n = Object.keys(i.prompts || {}).filter((k) => promptIds.includes(k)).length;
    const pers = i.personas || {};
    const personas = ['sales_agent', 'loans_agent', 'admin'].map((k) => pers[k]?.short || '-').join(' / ');
    const tools = p ? `${p.tools.filter((t) => t.persona === 'ops').length} / ${p.tools.filter((t) => t.persona === 'insights').length} / ${p.tools.length}` : '-';
    const themes = themesFor(i.id);
    L.push(`| ${esc(i.label)} (\`${i.id}\`)${i.source === 'built-in' ? '' : ' *(added)*'} | ${i.id === 'generic' ? 'defaults' : `${n}/${promptIds.length}`} | ${esc(personas)} | ${p ? `\`${p.proxy}\` ${p.basePath}` : 'generic `/mcp`'} | ${tools} | ${p ? 'Industry agents' : 'Generic agents'} | ${themes.length ? esc(themes.join(', ')) : '-'} |`);
  }
  L.push('');
  L.push('## Themes');
  L.push('');
  L.push(`Theme library snapshot (${snap.themes.length} themes). Refresh with \`node industries/mapping.mjs --refresh-themes\` while the UI server runs.`);
  L.push('');
  L.push('| Theme | Industry | Pack |');
  L.push('|---|---|---|');
  for (const t of snap.themes) L.push(`| ${esc(t.name)} (\`${t.id}\`) | \`${t.industry}\` | ${byId.has(t.industry) ? `yes (\`${byId.get(t.industry).proxy}\`)` : 'no: generic tools'} |`);
  L.push('');
  L.push('## Packs');
  for (const p of allPacks) {
    L.push('');
    L.push(`### ${p.label} (\`${p.id}\`)`);
    L.push('');
    L.push(`- **MCP server:** Apigee proxy \`${p.proxy}\` at \`${p.basePath}\`, backed by Cloud Run \`industry-apis\` (\`services/packs/${p.id}.js\`).`);
    L.push(`- **Apigee products:** ${['ops', 'insights', 'admin'].map((k) => `\`${p.personas[k].product}\` (${k === 'admin' ? 'admin key, ungoverned agent' : `${p.personas[k].role}, ${p.personas[k].app}`})`).join('; ')}.`);
    L.push(`- **Business limit:** \`${p.limit.tool}\` over $${p.limit.max} → 403 \`${p.limit.code}\` for the ops product.`);
    const areas = (persona) => [...new Set(p.tools.filter((t) => t.persona === persona).map((t) => t.area))].join(', ');
    L.push(`- **Areas:** ops: ${areas('ops')}; insights: ${areas('insights')}.`);
    L.push(`- **Story:** ${p.story.summary}`);
    L.push('');
    L.push('| Showcase scenario | Prompt |');
    L.push('|---|---|');
    for (const [slot, s] of Object.entries(p.showcase.scenarios)) L.push(`| ${slot}: ${esc(s.title)} | ${esc(s.prompt)} |`);
  }
  L.push('');
  return L.join('\n');
}

async function main() {
  const args = process.argv.slice(2);
  if (args[0] === '--refresh-themes') await refreshThemes(args[1] || 'http://localhost:3000/api/themes');
  const want = render();
  if (args.includes('--check')) {
    const have = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
    if (have !== want) {
      console.error('industries/MAPPING.md is stale. Run: node industries/mapping.mjs');
      process.exit(1);
    }
    console.log('industries/MAPPING.md in sync');
    return;
  }
  fs.writeFileSync(OUT, want);
  console.log('wrote industries/MAPPING.md');
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
