#!/usr/bin/env node
// Copies the industry packs (and the validator) next to each consumer.
//
// Each consumer is built from its own directory (Cloud Run / Docker build context), so the
// packs cannot be read from the repo root at runtime. This script keeps committed copies in
// step with industries/. Tests fail if a copy is stale (`node industries/sync.js --check`).
//
//   node industries/sync.js           # write the copies
//   node industries/sync.js --check   # exit 1 if any copy differs

'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { validatePack } = require('./validate');

const SRC = __dirname;
const ROOT = path.dirname(SRC);
/** Consumer directories that get a copy. */
const TARGETS = ['services/industries', 'agents/app/industries'];
/** The UI gets one generated ES module (Vite and the Node unit tests both import it). */
const UI_MODULE = 'ui/src/data/industryPacks.js';

function uiModule(files) {
  const packs = files.filter((f) => f.endsWith('.json')).map((f) => JSON.parse(fs.readFileSync(path.join(SRC, f), 'utf8')));
  return [
    '// Generated by industries/sync.js from industries/*.json. Do not edit by hand.',
    '// Run `node industries/sync.js` after changing a pack.',
    '',
    `export const INDUSTRY_PACKS = ${JSON.stringify(packs, null, 2)};`,
    '',
    'export default INDUSTRY_PACKS;',
    '',
  ].join('\n');
}

/** The UI server cannot import src/, so it gets just the pack Admin product names. */
const SERVER_MODULE = 'ui/server/industryAdminProducts.js';

function serverModule(files) {
  const names = files.filter((f) => f.endsWith('.json'))
    .map((f) => JSON.parse(fs.readFileSync(path.join(SRC, f), 'utf8')).personas.admin.product);
  return [
    '// Generated by industries/sync.js from industries/*.json. Do not edit by hand.',
    '// Admin MCP product of every industry pack; admins\' apps get them on sign-in.',
    '',
    `export const INDUSTRY_ADMIN_PRODUCTS = ${JSON.stringify(names, null, 2)};`,
    '',
  ].join('\n');
}

function sourceFiles() {
  return fs.readdirSync(SRC).filter((f) => f.endsWith('.json') || f === 'validate.js').sort();
}

function main() {
  const check = process.argv.includes('--check');
  const files = sourceFiles();
  for (const f of files.filter((x) => x.endsWith('.json'))) {
    const errors = validatePack(JSON.parse(fs.readFileSync(path.join(SRC, f), 'utf8')));
    if (errors.length) {
      console.error(`${f}: invalid pack\n  - ${errors.join('\n  - ')}`);
      process.exit(1);
    }
  }
  let stale = 0;
  for (const t of TARGETS) {
    const dir = path.join(ROOT, t);
    fs.mkdirSync(dir, { recursive: true });
    for (const f of files) {
      const want = fs.readFileSync(path.join(SRC, f), 'utf8');
      const dest = path.join(dir, f);
      const have = fs.existsSync(dest) ? fs.readFileSync(dest, 'utf8') : null;
      if (have === want) continue;
      stale++;
      if (check) console.error(`stale: ${t}/${f}`);
      else fs.writeFileSync(dest, want);
    }
    // Remove copies whose source was deleted.
    for (const f of fs.readdirSync(dir)) {
      if ((f.endsWith('.json') || f === 'validate.js') && !files.includes(f)) {
        stale++;
        if (check) console.error(`orphan: ${t}/${f}`);
        else fs.unlinkSync(path.join(dir, f));
      }
    }
  }
  const uiPath = path.join(ROOT, UI_MODULE);
  const wantUi = uiModule(files);
  if (!fs.existsSync(uiPath) || fs.readFileSync(uiPath, 'utf8') !== wantUi) {
    stale++;
    if (check) console.error(`stale: ${UI_MODULE}`);
    else { fs.mkdirSync(path.dirname(uiPath), { recursive: true }); fs.writeFileSync(uiPath, wantUi); }
  }
  const serverPath = path.join(ROOT, SERVER_MODULE);
  const wantServer = serverModule(files);
  if (!fs.existsSync(serverPath) || fs.readFileSync(serverPath, 'utf8') !== wantServer) {
    stale++;
    if (check) console.error(`stale: ${SERVER_MODULE}`);
    else fs.writeFileSync(serverPath, wantServer);
  }
  if (check && stale) {
    console.error('Run: node industries/sync.js');
    process.exit(1);
  }
  console.log(check ? 'industry packs in sync' : `synced ${files.length} files to ${[...TARGETS, UI_MODULE, SERVER_MODULE].join(', ')}${stale ? '' : ' (no changes)'}`);
}

main();
