// Generated by industries/sync.js from industries/*.json. Do not edit by hand.
// Admin MCP product of every industry pack; admins' apps get them on sign-in.

export const INDUSTRY_ADMIN_PRODUCTS = [
  "Aviation Tools MCP Admin",
  "Banking Tools MCP Admin",
  "Education Tools MCP Admin",
  "Energy Tools MCP Admin",
  "Healthcare Tools MCP Admin",
  "Insurance Tools MCP Admin",
  "IT Services Tools MCP Admin",
  "Manufacturing Tools MCP Admin",
  "Media Tools MCP Admin",
  "Oil and Gas Tools MCP Admin",
  "Public Sector Tools MCP Admin",
  "Real Estate Tools MCP Admin",
  "Retail Tools MCP Admin",
  "Telecom Tools MCP Admin",
  "Travel Tools MCP Admin"
];
